baseURL = "http://raindev.io"
languageCode = "en-us"
title = "raindev | Andrew's Blog"
theme = "hugo-bearblog"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
lineNos = true

[params]
favicon = "static/favicon.png"

[[menu.main]]
name = "All Posts"
identifier = "posts"
url = "/blog/"
weight = 1

[[menu.main]]
name = "Contact"
identifier = "contact"
url = "/contact/"
weight = 2

[[menu.main]]
name = "About"
identifier = "about"
url = "/about/"
weight = 3
