baseURL = "http://raindev.io"
languageCode = "en-us"
title = "raindev | Andrew's Blog"
theme = "hugo-bearblog"

[markup.goldmark.renderer]
	unsafe = true

[params]
  style = "auto"
  rssAsSocialIcon = true
  customCSS = [ "custom.css" ]
  favicon = "static/favicon.png"

[[params.social]]
id = "github"
name = "raindev"

[[params.social]]
id = "bluesky"
name = "raindev.io"

[[params.social]]
id = "email"
name = "andrew@raindev.io"

[[menu.main]]
name = "All Posts"
identifier = "posts"
url = "/blog/"
weight = 1

[[menu.main]]
name = "Contact"
identifier = "contact"
url = "/contact/"
weight = 2

[[menu.main]]
name = "About"
identifier = "about"
url = "/about/"
weight = 3
